### ISSUE TITLE
Missing mod(s)

### ISSUE THREAD

**Issue by Knha1ex** [KT-55/Calvin-s-From-The-Fog#2]
I love your modpack, but I was a bit disappointed when I noticed that there's no Alex, and signs don't get left around, maybe I just haven't experienced that yet, I've only played it for a couple hours. But I'd really hope you could add that(if it's not already there) and if it is, then I'll find out soon. Thank you and have a good day.

**Comment by KT-55** [comment]
ok i do see your problem, and I will do my best to explain (sorry for the late reply)
- The alex thing is just herobrine retextured. to retexture him run the command "/function fromthefog:admin/config" and go to page 2, and there is where u can see the option to change the skin
- The sign thing is one of Calvins friends placing them as no herobrine mod does that.
